[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
veriagent_pay = "9QQaAmTaW6FR3q8qYnAoCFr8kcmKwPE99terRZ95txmR"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000