[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
veriagent_pay = "AJirAN6RarZXyHWfYLSFB6NUCbFG3RaKDXMCDueRi7uV"

[programs.devnet]
veriagent_pay = "AJirAN6RarZXyHWfYLSFB6NUCbFG3RaKDXMCDueRi7uV"

[provider]
cluster = "Devnet"
wallet = "../../.keys/devnet-deployer.json"

[test]
startup_wait = 10000